### ISSUE TITLE
查询历史数据错误

### ISSUE THREAD

**Issue by chixu-xmu** [PieceOfFall/SmartHouseSystem#49]
![ff1748745ec4489687eca7c336bba280](https://github.com/PieceOfFall/SmartHouseSystem/assets/96009465/3eefa68f-d671-4cef-9d3d-0b4a7d6f5614)

<img width="1407" alt="image" src="https://github.com/PieceOfFall/SmartHouseSystem/assets/96009465/30aafe11-c6c2-4b73-b782-042516040775">

<img width="1407" alt="image" src="https://github.com/PieceOfFall/SmartHouseSystem/assets/96009465/74476369-6514-40dc-a29c-1f482a8c4663">

**Comment by PieceOfFall** [comment]
请给出前端控制台报错信息

**Comment by chixu-xmu** [comment]
> 

前端无报错信息，能查询历史数据，但历史数据不对应查询条件，例如查询近三天，系统则展示1970年

**Comment by chixu-xmu** [comment]
<img width="848" alt="image" src="https://github.com/PieceOfFall/SmartHouseSystem/assets/96009465/24e9b5e4-2a93-44f7-9d52-eb78d3548ac1">

`类型 DefineComponent<{}, {}, {}, import("vue").ComputedOptions, import("vue").MethodOptions, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{}>>, {}> 不可分配给类型 string | Component`

**Comment by PieceOfFall** [comment]
传感器你开了吗

**Comment by PieceOfFall** [comment]
传感器是sensor文件夹下的app.js文件。你要先开启后端再开这个传感器文件

**Comment by PieceOfFall** [comment]
如果传感器开了，那么你试着在这个QueryCertainData组件的第66行下面试着打印一下date.getFullYear()

**Comment by chixu-xmu** [comment]
<img width="1185" alt="image" src="https://github.com/PieceOfFall/SmartHouseSystem/assets/96009465/e4a05e34-3442-4fa3-a477-d9a8c3195da7">
这样吗？因为没学过前端，不是很懂这方面的调试
